// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwrjdzldsehxkwdjfqhs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3cmpkemxkc2VoeGt3ZGpmcWhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MjE1MzQsImV4cCI6MjA2MTE5NzUzNH0.YLw0znm1puhX967Fl8PxjUc1lFXumWdHjfXuyB829jc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);